- name: 'Plaintext View'
  uriPattern: '{node}.plaintext'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
    'plaintext': true
  appendExceedingArguments: true
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
