Garagist:
  Plaintext:
    imageAltText: true

    # false
    # 'inline' (show links inline)
    # 'nextline' (show links on the next line)
    # 'table' (if a table of link URLs should be listed after the text.
    # 'bbcode' (show links as bbcode)
    links: inline

    #  Maximum width of the formatted text, in columns.
    #  Set this value to 0 (or less) to ignore word wrapping
    #  and not constrain text to a fixed-width column.
    width: 70
